version: '3.4'

services:
  go-redis-crypto:
    image: go-redis-crypto
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 1525:1525
    links:
      - redis
  redis:
    image: redis
    ports:
    - "6379:6379"